<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <TiaPortalPublicApi Condition="'$(TiaPortalPublicApi)' == ''">$(ProgramFiles)\Siemens\Automation\Portal V21\PublicAPI\V21\net48</TiaPortalPublicApi>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="Siemens.Engineering.Base">
      <HintPath>$(TiaPortalPublicApi)\Siemens.Engineering.Base.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Siemens.Engineering.Step7">
      <HintPath>$(TiaPortalPublicApi)\Siemens.Engineering.Step7.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
